name: Laravel

on:
  push:
    branches: [ "main", "Cote-cambios" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Setup environment
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Skip tests
      run: echo "No tests configured"